### ISSUE TITLE
**REMOTE_ISF_URL

### ISSUE THREAD

**Issue by gunner4361** [leludo84/vol3-linux-profiles#2]
python3 vol.py -f /mnt/d/13/linux/u-server.mem linux.pslist
Traceback (most recent call last):
  File "/home/ben/tools/volatility3/vol.py", line 8, in <module>
    import volatility3.cli
  File "/home/ben/tools/volatility3/volatility3/cli/__init__.py", line 32, in <module>
    from volatility3.cli import text_filter
  File "/home/ben/tools/volatility3/volatility3/cli/text_filter.py", line 3, in <module>
    from volatility3.framework import constants, interfaces
  File "/home/ben/tools/volatility3/volatility3/framework/__init__.py", line 32, in <module>
    from volatility3.framework import constants, interfaces
  File "/home/ben/tools/volatility3/volatility3/framework/constants/__init__.py", line 114
    **REMOTE_ISF_URL =https://raw.githubusercontent.com/leludo84/vol3-linux-profiles/main/banners-isf.json**
                         ^
SyntaxError: invalid syntax

**Comment by leludo84** [comment]
Did you put double quotes around the URL ?

**Comment by gunner4361** [comment]
Thank you the "" worked

**Comment by leludo84** [comment]
you're welcome.
